### ISSUE TITLE
项目任务：使用国境内部节点和国境外部节点连通部署

### ISSUE THREAD

**Issue by JulienGuo** [HyperLedgerChain/ProjectTaskCenter#4]
跨境跨的是日本和新加坡，不知道跨国境会怎么样，要连接国内节点测试，测试代码和readme上传到GitHub

**Comment by yuqian0218** [comment]
@JulienGuo 这个任务的具体需求是什么？我可以在公司北京机房的服务器上跑一套节点起来，连通部署的话是需要跟谁配合嘛？

**Comment by JulienGuo** [comment]
> @JulienGuo 这个任务的具体需求是什么？我可以在公司北京机房的服务器上跑一套节点起来，连通部署的话是需要跟谁配合嘛？

你好，谢谢关注。
这个问题第四周调试过了，忘记关闭。现在有其他那些issue的问题。
